# Generated by Django 5.0.1 on 2024-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userdetail_icici_key_alter_userdetail_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
